{"name": "test_sign_up_invalid_bn_number2", "status": "passed", "description": "the test is verify, that user can't sign up with invalid business number", "start": 1680536585411, "stop": 1680536586136, "uuid": "3947c5dd-f567-4f72-836e-3befce79e145", "historyId": "d643a13b2f2ede47d283474b3f054ce0", "testCaseId": "5ec97021808c1505f75ad6c5153647f4", "fullName": "tests.edgeTests.testSignUpModal.TestSignUpModal#test_sign_up_invalid_bn_number2", "labels": [{"name": "parentSuite", "value": "tests.edgeTests"}, {"name": "suite", "value": "testSignUpModal"}, {"name": "subSuite", "value": "TestSignUpModal"}, {"name": "host", "value": "krot"}, {"name": "thread", "value": "19772-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.edgeTests.testSignUpModal"}]}