{"name": "test_sign_in_invalid_number3", "status": "passed", "description": "the test is verify, that user can't sign in with invalid number", "start": 1680369552265, "stop": 1680369552941, "uuid": "8e91f69e-8d7b-47ba-9592-a0680790f193", "historyId": "dabe8d32e9092b65d088595cce499c54", "testCaseId": "2f9c637aa208880775684f7c53f0bed4", "fullName": "tests.chromeTests.testSignInModal.TestSignInModal#test_sign_in_invalid_number3", "labels": [{"name": "parentSuite", "value": "tests.chromeTests"}, {"name": "suite", "value": "testSignInModal"}, {"name": "subSuite", "value": "TestSignInModal"}, {"name": "host", "value": "krot"}, {"name": "thread", "value": "8896-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.chromeTests.testSignInModal"}]}