{"name": "test_sign_in_invalid_number2", "status": "passed", "description": "the test is verify, that user can't sign in with invalid number", "start": 1680348655829, "stop": 1680348656523, "uuid": "b33001ae-02cd-4c08-ad31-75788f674dc1", "historyId": "ea8c01d8f5483842d320f0ec128d2b65", "testCaseId": "95bbff77084e815a11fcd7db429e0e12", "fullName": "tests.chromeTests.testSignInModal.TestSignInModal#test_sign_in_invalid_number2", "labels": [{"name": "parentSuite", "value": "tests.chromeTests"}, {"name": "suite", "value": "testSignInModal"}, {"name": "subSuite", "value": "TestSignInModal"}, {"name": "host", "value": "krot"}, {"name": "thread", "value": "12616-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.chromeTests.testSignInModal"}]}