{"name": "test_sign_up_invalid_phone_num1", "status": "passed", "description": "the test is verify, that user can't sign up with invalid phone number", "start": 1680536560596, "stop": 1680536561359, "uuid": "f151b4dd-fcc7-4e00-b0e2-0b95e22e73a1", "historyId": "8a175dfdb7dac719ca37454f8692d619", "testCaseId": "e0bfc1a843f0f7a80682e9da1b35e82f", "fullName": "tests.edgeTests.testSignUpModal.TestSignUpModal#test_sign_up_invalid_phone_num1", "labels": [{"name": "parentSuite", "value": "tests.edgeTests"}, {"name": "suite", "value": "testSignUpModal"}, {"name": "subSuite", "value": "TestSignUpModal"}, {"name": "host", "value": "krot"}, {"name": "thread", "value": "19772-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.edgeTests.testSignUpModal"}]}