{"name": "test_sign_in_invalid_number1", "status": "passed", "description": "the test is verify, that user can't sign in with invalid number", "start": 1680535641891, "stop": 1680535643113, "uuid": "fdd72fda-7280-434e-8df3-fe1563c9e411", "historyId": "618a6abfbb03d995734ca6085fd39bd8", "testCaseId": "4bbb6a755fd45f51b72a4c785634f14a", "fullName": "tests.chromeTests.testSignInModal.TestSignInModal#test_sign_in_invalid_number1", "labels": [{"name": "parentSuite", "value": "tests.chromeTests"}, {"name": "suite", "value": "testSignInModal"}, {"name": "subSuite", "value": "TestSignInModal"}, {"name": "host", "value": "krot"}, {"name": "thread", "value": "19772-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.chromeTests.testSignInModal"}]}