{"name": "test_sign_in_invalid_number2", "status": "passed", "description": "the test is verify, that user can't sign in with invalid number", "start": 1680369546547, "stop": 1680369547225, "uuid": "4a128ae4-e69c-40a7-9ecc-f0dab78b2ec3", "historyId": "ea8c01d8f5483842d320f0ec128d2b65", "testCaseId": "95bbff77084e815a11fcd7db429e0e12", "fullName": "tests.chromeTests.testSignInModal.TestSignInModal#test_sign_in_invalid_number2", "labels": [{"name": "parentSuite", "value": "tests.chromeTests"}, {"name": "suite", "value": "testSignInModal"}, {"name": "subSuite", "value": "TestSignInModal"}, {"name": "host", "value": "krot"}, {"name": "thread", "value": "8896-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.chromeTests.testSignInModal"}]}