{"name": "test_sign_up_invalid_phone_num3", "status": "passed", "description": "the test is verify, that user can't sign up with invalid phone number", "start": 1680536572264, "stop": 1680536573044, "uuid": "f479f17d-a87d-45bd-8e29-2d178d838065", "historyId": "8c10c104f23a38443464bc7dc84d5ac8", "testCaseId": "ce69a1d32cb4983a1ca7ba178ab01e76", "fullName": "tests.edgeTests.testSignUpModal.TestSignUpModal#test_sign_up_invalid_phone_num3", "labels": [{"name": "parentSuite", "value": "tests.edgeTests"}, {"name": "suite", "value": "testSignUpModal"}, {"name": "subSuite", "value": "TestSignUpModal"}, {"name": "host", "value": "krot"}, {"name": "thread", "value": "19772-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.edgeTests.testSignUpModal"}]}