{"name": "test_sign_up_invalid_phone_num2", "status": "passed", "description": "the test is verify, that user can't sign up with invalid phone number", "start": 1680536566623, "stop": 1680536567390, "uuid": "cfa1a57f-8d6d-4afb-b518-dd4fbf2b0bf0", "historyId": "9c09c7fd208a54177cd8d24b069493f9", "testCaseId": "114d9b0d63e6071b5927d7c3130dfcfe", "fullName": "tests.edgeTests.testSignUpModal.TestSignUpModal#test_sign_up_invalid_phone_num2", "labels": [{"name": "parentSuite", "value": "tests.edgeTests"}, {"name": "suite", "value": "testSignUpModal"}, {"name": "subSuite", "value": "TestSignUpModal"}, {"name": "host", "value": "krot"}, {"name": "thread", "value": "19772-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.edgeTests.testSignUpModal"}]}