{"name": "test_sign_in_invalid_number1", "status": "passed", "description": "the test is verify, that user can't sign in with invalid number", "start": 1680369540638, "stop": 1680369541876, "uuid": "402182ac-d850-4df1-8cb5-9f1d715e61f8", "historyId": "618a6abfbb03d995734ca6085fd39bd8", "testCaseId": "4bbb6a755fd45f51b72a4c785634f14a", "fullName": "tests.chromeTests.testSignInModal.TestSignInModal#test_sign_in_invalid_number1", "labels": [{"name": "parentSuite", "value": "tests.chromeTests"}, {"name": "suite", "value": "testSignInModal"}, {"name": "subSuite", "value": "TestSignInModal"}, {"name": "host", "value": "krot"}, {"name": "thread", "value": "8896-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.chromeTests.testSignInModal"}]}