{"name": "test_sign_in_invalid_number3", "status": "passed", "description": "the test is verify, that user can't sign in with invalid number", "start": 1680348661248, "stop": 1680348661927, "uuid": "73c6a6b5-9417-4bf7-8665-f932369e243f", "historyId": "dabe8d32e9092b65d088595cce499c54", "testCaseId": "2f9c637aa208880775684f7c53f0bed4", "fullName": "tests.chromeTests.testSignInModal.TestSignInModal#test_sign_in_invalid_number3", "labels": [{"name": "parentSuite", "value": "tests.chromeTests"}, {"name": "suite", "value": "testSignInModal"}, {"name": "subSuite", "value": "TestSignInModal"}, {"name": "host", "value": "krot"}, {"name": "thread", "value": "12616-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.chromeTests.testSignInModal"}]}